os:
  - osx
  - linux

language: go

go:
  - 1.x
  - tip

install:
  - go get -t -v scientificgo.org/testutil/...
  
script:
  - go test scientificgo.org/testutil/... -bench=. -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 0

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
